from collections import Counter

counter = Counter()
print(counter)
counter.update("안녕하세요.")
print(counter)
counter.update("안녕.")
print(counter)
counter.update({"안":3, "요":5})
print(counter)
counter.update("나")
print(counter)
print('--' * 10)

mostCommon = counter.most_common(3)
print("most_common(3):", mostCommon)
print('--' * 10)

c1 = Counter("반갑습니다.안녕하세요.")
c2 = Counter("반갑다.친구야.")
print(c1)
print(c2)
c1.subtract(c2)
print("c1.subtract(c2): ", c1)
print('--' * 10)

c1 = Counter(["a", "b", "c", "d", "a"])
c2 = Counter("apple")
print("c1:", c1)
print("c2:", c2)
print("c1 + c2: ", c1 + c2)
print("c1 - c2: ", c1 - c2)
print('--' * 10)

c1 = Counter("abcdefg")
c2 = Counter("abcdxyz")
print("c1 & c2: ", c1 & c2)
print("c1 | c2: ", c1 | c2)
print('--' * 10)

